<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace DockerPhpClient\Compose\Normalizer;

class NormalizerFactory
{
    public static function create()
    {
        $normalizers = [];
        $normalizers[] = new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer();
        $normalizers[] = new \Jane\JsonSchemaRuntime\Normalizer\ReferenceNormalizer();
        $normalizers[] = new FileNormalizer();
        $normalizers[] = new ServiceNormalizer();
        $normalizers[] = new ServiceCredentialSpecNormalizer();
        $normalizers[] = new ServiceLoggingNormalizer();
        $normalizers[] = new HealthcheckNormalizer();
        $normalizers[] = new GenericResourcesItemNormalizer();
        $normalizers[] = new GenericResourcesItemDiscreteResourceSpecNormalizer();
        $normalizers[] = new SecretNormalizer();
        $normalizers[] = new ConfigNormalizer();

        return $normalizers;
    }
}
