<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace DockerPhpClient\Compose\Model;

class File extends \ArrayObject
{
    /**
     * @var string
     */
    protected $version;
    /**
     * @var Service[]
     */
    protected $services;
    /**
     * @var object|null[]
     */
    protected $networks;
    /**
     * @var object|null[]
     */
    protected $volumes;
    /**
     * @var Secret[]
     */
    protected $secrets;
    /**
     * @var Config[]
     */
    protected $configs;

    /**
     * @return string
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * @param string $version
     *
     * @return self
     */
    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }

    /**
     * @return Service[]
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * @param Service[] $services
     *
     * @return self
     */
    public function setServices($services): self
    {
        $this->services = $services;

        return $this;
    }

    /**
     * @return object|null[]
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * @param object|null[] $networks
     *
     * @return self
     */
    public function setNetworks($networks): self
    {
        $this->networks = $networks;

        return $this;
    }

    /**
     * @return object|null[]
     */
    public function getVolumes()
    {
        return $this->volumes;
    }

    /**
     * @param object|null[] $volumes
     *
     * @return self
     */
    public function setVolumes($volumes): self
    {
        $this->volumes = $volumes;

        return $this;
    }

    /**
     * @return Secret[]
     */
    public function getSecrets()
    {
        return $this->secrets;
    }

    /**
     * @param Secret[] $secrets
     *
     * @return self
     */
    public function setSecrets($secrets): self
    {
        $this->secrets = $secrets;

        return $this;
    }

    /**
     * @return Config[]
     */
    public function getConfigs()
    {
        return $this->configs;
    }

    /**
     * @param Config[] $configs
     *
     * @return self
     */
    public function setConfigs($configs): self
    {
        $this->configs = $configs;

        return $this;
    }
}
