<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace DockerPhpClient\Compose\Model;

class Healthcheck
{
    /**
     * @var bool
     */
    protected $disable;
    /**
     * @var string
     */
    protected $interval;
    /**
     * @var float
     */
    protected $retries;
    /**
     * @var string|string[]
     */
    protected $test;
    /**
     * @var string
     */
    protected $timeout;
    /**
     * @var string
     */
    protected $startPeriod;

    /**
     * @return bool
     */
    public function getDisable(): ?bool
    {
        return $this->disable;
    }

    /**
     * @param bool $disable
     *
     * @return self
     */
    public function setDisable(?bool $disable): self
    {
        $this->disable = $disable;

        return $this;
    }

    /**
     * @return string
     */
    public function getInterval(): ?string
    {
        return $this->interval;
    }

    /**
     * @param string $interval
     *
     * @return self
     */
    public function setInterval(?string $interval): self
    {
        $this->interval = $interval;

        return $this;
    }

    /**
     * @return float
     */
    public function getRetries(): ?float
    {
        return $this->retries;
    }

    /**
     * @param float $retries
     *
     * @return self
     */
    public function setRetries(?float $retries): self
    {
        $this->retries = $retries;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getTest()
    {
        return $this->test;
    }

    /**
     * @param string|string[] $test
     *
     * @return self
     */
    public function setTest($test): self
    {
        $this->test = $test;

        return $this;
    }

    /**
     * @return string
     */
    public function getTimeout(): ?string
    {
        return $this->timeout;
    }

    /**
     * @param string $timeout
     *
     * @return self
     */
    public function setTimeout(?string $timeout): self
    {
        $this->timeout = $timeout;

        return $this;
    }

    /**
     * @return string
     */
    public function getStartPeriod(): ?string
    {
        return $this->startPeriod;
    }

    /**
     * @param string $startPeriod
     *
     * @return self
     */
    public function setStartPeriod(?string $startPeriod): self
    {
        $this->startPeriod = $startPeriod;

        return $this;
    }
}
