<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace DockerPhpClient\Compose\Model;

class Secret extends \ArrayObject
{
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $file;
    /**
     * @var bool|object
     */
    protected $external;
    /**
     * @var string|float|null[]|string[]
     */
    protected $labels;

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getFile(): ?string
    {
        return $this->file;
    }

    /**
     * @param string $file
     *
     * @return self
     */
    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @return bool|object
     */
    public function getExternal()
    {
        return $this->external;
    }

    /**
     * @param bool|object $external
     *
     * @return self
     */
    public function setExternal($external): self
    {
        $this->external = $external;

        return $this;
    }

    /**
     * @return string|float|null[]|string[]
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * @param string|float|null[]|string[] $labels
     *
     * @return self
     */
    public function setLabels($labels): self
    {
        $this->labels = $labels;

        return $this;
    }
}
