<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace DockerPhpClient\Compose\Model;

class ServiceLogging
{
    /**
     * @var string
     */
    protected $driver;
    /**
     * @var string|float|null[]
     */
    protected $options;

    /**
     * @return string
     */
    public function getDriver(): ?string
    {
        return $this->driver;
    }

    /**
     * @param string $driver
     *
     * @return self
     */
    public function setDriver(?string $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * @return string|float|null[]
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * @param string|float|null[] $options
     *
     * @return self
     */
    public function setOptions($options): self
    {
        $this->options = $options;

        return $this;
    }
}
