<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace DockerPhpClient\Compose\Model;

class Service extends \ArrayObject
{
    /**
     * @var object|null
     */
    protected $deploy;
    /**
     * @var string|object
     */
    protected $build;
    /**
     * @var string[]
     */
    protected $capAdd;
    /**
     * @var string[]
     */
    protected $capDrop;
    /**
     * @var string
     */
    protected $cgroupParent;
    /**
     * @var string|string[]
     */
    protected $command;
    /**
     * @var string[]|object[]
     */
    protected $configs;
    /**
     * @var string
     */
    protected $containerName;
    /**
     * @var ServiceCredentialSpec
     */
    protected $credentialSpec;
    /**
     * @var string[]
     */
    protected $dependsOn;
    /**
     * @var string[]
     */
    protected $devices;
    /**
     * @var string|string[]
     */
    protected $dns;
    /**
     * @var string|string[]
     */
    protected $dnsSearch;
    /**
     * @var string
     */
    protected $domainname;
    /**
     * @var string|string[]
     */
    protected $entrypoint;
    /**
     * @var string|string[]
     */
    protected $envFile;
    /**
     * @var string|float|null[]|string[]
     */
    protected $environment;
    /**
     * @var string[]|float[]
     */
    protected $expose;
    /**
     * @var string[]
     */
    protected $externalLinks;
    /**
     * @var string|float|null[]|string[]
     */
    protected $extraHosts;
    /**
     * @var Healthcheck
     */
    protected $healthcheck;
    /**
     * @var string
     */
    protected $hostname;
    /**
     * @var string
     */
    protected $image;
    /**
     * @var string
     */
    protected $ipc;
    /**
     * @var string
     */
    protected $isolation;
    /**
     * @var string|float|null[]|string[]
     */
    protected $labels;
    /**
     * @var string[]
     */
    protected $links;
    /**
     * @var ServiceLogging
     */
    protected $logging;
    /**
     * @var string
     */
    protected $macAddress;
    /**
     * @var string
     */
    protected $networkMode;
    /**
     * @var string[]|object|null[]
     */
    protected $networks;
    /**
     * @var string|null
     */
    protected $pid;
    /**
     * @var float[]|string[]|object[]
     */
    protected $ports;
    /**
     * @var bool
     */
    protected $privileged;
    /**
     * @var bool
     */
    protected $readOnly;
    /**
     * @var string
     */
    protected $restart;
    /**
     * @var string[]
     */
    protected $securityOpt;
    /**
     * @var float|string
     */
    protected $shmSize;
    /**
     * @var string[]|object[]
     */
    protected $secrets;
    /**
     * @var string|float|null[]|string[]
     */
    protected $sysctls;
    /**
     * @var bool
     */
    protected $stdinOpen;
    /**
     * @var string
     */
    protected $stopGracePeriod;
    /**
     * @var string
     */
    protected $stopSignal;
    /**
     * @var string|string[]
     */
    protected $tmpfs;
    /**
     * @var bool
     */
    protected $tty;
    /**
     * @var int|object[]
     */
    protected $ulimits;
    /**
     * @var string
     */
    protected $user;
    /**
     * @var string
     */
    protected $usernsMode;
    /**
     * @var string[]|object[]
     */
    protected $volumes;
    /**
     * @var string
     */
    protected $workingDir;

    /**
     * @return object|null
     */
    public function getDeploy()
    {
        return $this->deploy;
    }

    /**
     * @param object|null $deploy
     *
     * @return self
     */
    public function setDeploy($deploy): self
    {
        $this->deploy = $deploy;

        return $this;
    }

    /**
     * @return string|object
     */
    public function getBuild()
    {
        return $this->build;
    }

    /**
     * @param string|object $build
     *
     * @return self
     */
    public function setBuild($build): self
    {
        $this->build = $build;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getCapAdd(): ?array
    {
        return $this->capAdd;
    }

    /**
     * @param string[] $capAdd
     *
     * @return self
     */
    public function setCapAdd(?array $capAdd): self
    {
        $this->capAdd = $capAdd;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getCapDrop(): ?array
    {
        return $this->capDrop;
    }

    /**
     * @param string[] $capDrop
     *
     * @return self
     */
    public function setCapDrop(?array $capDrop): self
    {
        $this->capDrop = $capDrop;

        return $this;
    }

    /**
     * @return string
     */
    public function getCgroupParent(): ?string
    {
        return $this->cgroupParent;
    }

    /**
     * @param string $cgroupParent
     *
     * @return self
     */
    public function setCgroupParent(?string $cgroupParent): self
    {
        $this->cgroupParent = $cgroupParent;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getCommand()
    {
        return $this->command;
    }

    /**
     * @param string|string[] $command
     *
     * @return self
     */
    public function setCommand($command): self
    {
        $this->command = $command;

        return $this;
    }

    /**
     * @return string[]|object[]
     */
    public function getConfigs(): ?array
    {
        return $this->configs;
    }

    /**
     * @param string[]|object[] $configs
     *
     * @return self
     */
    public function setConfigs(?array $configs): self
    {
        $this->configs = $configs;

        return $this;
    }

    /**
     * @return string
     */
    public function getContainerName(): ?string
    {
        return $this->containerName;
    }

    /**
     * @param string $containerName
     *
     * @return self
     */
    public function setContainerName(?string $containerName): self
    {
        $this->containerName = $containerName;

        return $this;
    }

    /**
     * @return ServiceCredentialSpec
     */
    public function getCredentialSpec(): ?ServiceCredentialSpec
    {
        return $this->credentialSpec;
    }

    /**
     * @param ServiceCredentialSpec $credentialSpec
     *
     * @return self
     */
    public function setCredentialSpec(?ServiceCredentialSpec $credentialSpec): self
    {
        $this->credentialSpec = $credentialSpec;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getDependsOn(): ?array
    {
        return $this->dependsOn;
    }

    /**
     * @param string[] $dependsOn
     *
     * @return self
     */
    public function setDependsOn(?array $dependsOn): self
    {
        $this->dependsOn = $dependsOn;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getDevices(): ?array
    {
        return $this->devices;
    }

    /**
     * @param string[] $devices
     *
     * @return self
     */
    public function setDevices(?array $devices): self
    {
        $this->devices = $devices;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getDns()
    {
        return $this->dns;
    }

    /**
     * @param string|string[] $dns
     *
     * @return self
     */
    public function setDns($dns): self
    {
        $this->dns = $dns;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getDnsSearch()
    {
        return $this->dnsSearch;
    }

    /**
     * @param string|string[] $dnsSearch
     *
     * @return self
     */
    public function setDnsSearch($dnsSearch): self
    {
        $this->dnsSearch = $dnsSearch;

        return $this;
    }

    /**
     * @return string
     */
    public function getDomainname(): ?string
    {
        return $this->domainname;
    }

    /**
     * @param string $domainname
     *
     * @return self
     */
    public function setDomainname(?string $domainname): self
    {
        $this->domainname = $domainname;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getEntrypoint()
    {
        return $this->entrypoint;
    }

    /**
     * @param string|string[] $entrypoint
     *
     * @return self
     */
    public function setEntrypoint($entrypoint): self
    {
        $this->entrypoint = $entrypoint;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getEnvFile()
    {
        return $this->envFile;
    }

    /**
     * @param string|string[] $envFile
     *
     * @return self
     */
    public function setEnvFile($envFile): self
    {
        $this->envFile = $envFile;

        return $this;
    }

    /**
     * @return string|float|null[]|string[]
     */
    public function getEnvironment()
    {
        return $this->environment;
    }

    /**
     * @param string|float|null[]|string[] $environment
     *
     * @return self
     */
    public function setEnvironment($environment): self
    {
        $this->environment = $environment;

        return $this;
    }

    /**
     * @return string[]|float[]
     */
    public function getExpose(): ?array
    {
        return $this->expose;
    }

    /**
     * @param string[]|float[] $expose
     *
     * @return self
     */
    public function setExpose(?array $expose): self
    {
        $this->expose = $expose;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getExternalLinks(): ?array
    {
        return $this->externalLinks;
    }

    /**
     * @param string[] $externalLinks
     *
     * @return self
     */
    public function setExternalLinks(?array $externalLinks): self
    {
        $this->externalLinks = $externalLinks;

        return $this;
    }

    /**
     * @return string|float|null[]|string[]
     */
    public function getExtraHosts()
    {
        return $this->extraHosts;
    }

    /**
     * @param string|float|null[]|string[] $extraHosts
     *
     * @return self
     */
    public function setExtraHosts($extraHosts): self
    {
        $this->extraHosts = $extraHosts;

        return $this;
    }

    /**
     * @return Healthcheck
     */
    public function getHealthcheck(): ?Healthcheck
    {
        return $this->healthcheck;
    }

    /**
     * @param Healthcheck $healthcheck
     *
     * @return self
     */
    public function setHealthcheck(?Healthcheck $healthcheck): self
    {
        $this->healthcheck = $healthcheck;

        return $this;
    }

    /**
     * @return string
     */
    public function getHostname(): ?string
    {
        return $this->hostname;
    }

    /**
     * @param string $hostname
     *
     * @return self
     */
    public function setHostname(?string $hostname): self
    {
        $this->hostname = $hostname;

        return $this;
    }

    /**
     * @return string
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string $image
     *
     * @return self
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return string
     */
    public function getIpc(): ?string
    {
        return $this->ipc;
    }

    /**
     * @param string $ipc
     *
     * @return self
     */
    public function setIpc(?string $ipc): self
    {
        $this->ipc = $ipc;

        return $this;
    }

    /**
     * @return string
     */
    public function getIsolation(): ?string
    {
        return $this->isolation;
    }

    /**
     * @param string $isolation
     *
     * @return self
     */
    public function setIsolation(?string $isolation): self
    {
        $this->isolation = $isolation;

        return $this;
    }

    /**
     * @return string|float|null[]|string[]
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * @param string|float|null[]|string[] $labels
     *
     * @return self
     */
    public function setLabels($labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * @param string[] $links
     *
     * @return self
     */
    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }

    /**
     * @return ServiceLogging
     */
    public function getLogging(): ?ServiceLogging
    {
        return $this->logging;
    }

    /**
     * @param ServiceLogging $logging
     *
     * @return self
     */
    public function setLogging(?ServiceLogging $logging): self
    {
        $this->logging = $logging;

        return $this;
    }

    /**
     * @return string
     */
    public function getMacAddress(): ?string
    {
        return $this->macAddress;
    }

    /**
     * @param string $macAddress
     *
     * @return self
     */
    public function setMacAddress(?string $macAddress): self
    {
        $this->macAddress = $macAddress;

        return $this;
    }

    /**
     * @return string
     */
    public function getNetworkMode(): ?string
    {
        return $this->networkMode;
    }

    /**
     * @param string $networkMode
     *
     * @return self
     */
    public function setNetworkMode(?string $networkMode): self
    {
        $this->networkMode = $networkMode;

        return $this;
    }

    /**
     * @return string[]|object|null[]
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * @param string[]|object|null[] $networks
     *
     * @return self
     */
    public function setNetworks($networks): self
    {
        $this->networks = $networks;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPid(): ?string
    {
        return $this->pid;
    }

    /**
     * @param string|null $pid
     *
     * @return self
     */
    public function setPid(?string $pid): self
    {
        $this->pid = $pid;

        return $this;
    }

    /**
     * @return float[]|string[]|object[]
     */
    public function getPorts(): ?array
    {
        return $this->ports;
    }

    /**
     * @param float[]|string[]|object[] $ports
     *
     * @return self
     */
    public function setPorts(?array $ports): self
    {
        $this->ports = $ports;

        return $this;
    }

    /**
     * @return bool
     */
    public function getPrivileged(): ?bool
    {
        return $this->privileged;
    }

    /**
     * @param bool $privileged
     *
     * @return self
     */
    public function setPrivileged(?bool $privileged): self
    {
        $this->privileged = $privileged;

        return $this;
    }

    /**
     * @return bool
     */
    public function getReadOnly(): ?bool
    {
        return $this->readOnly;
    }

    /**
     * @param bool $readOnly
     *
     * @return self
     */
    public function setReadOnly(?bool $readOnly): self
    {
        $this->readOnly = $readOnly;

        return $this;
    }

    /**
     * @return string
     */
    public function getRestart(): ?string
    {
        return $this->restart;
    }

    /**
     * @param string $restart
     *
     * @return self
     */
    public function setRestart(?string $restart): self
    {
        $this->restart = $restart;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getSecurityOpt(): ?array
    {
        return $this->securityOpt;
    }

    /**
     * @param string[] $securityOpt
     *
     * @return self
     */
    public function setSecurityOpt(?array $securityOpt): self
    {
        $this->securityOpt = $securityOpt;

        return $this;
    }

    /**
     * @return float|string
     */
    public function getShmSize()
    {
        return $this->shmSize;
    }

    /**
     * @param float|string $shmSize
     *
     * @return self
     */
    public function setShmSize($shmSize): self
    {
        $this->shmSize = $shmSize;

        return $this;
    }

    /**
     * @return string[]|object[]
     */
    public function getSecrets(): ?array
    {
        return $this->secrets;
    }

    /**
     * @param string[]|object[] $secrets
     *
     * @return self
     */
    public function setSecrets(?array $secrets): self
    {
        $this->secrets = $secrets;

        return $this;
    }

    /**
     * @return string|float|null[]|string[]
     */
    public function getSysctls()
    {
        return $this->sysctls;
    }

    /**
     * @param string|float|null[]|string[] $sysctls
     *
     * @return self
     */
    public function setSysctls($sysctls): self
    {
        $this->sysctls = $sysctls;

        return $this;
    }

    /**
     * @return bool
     */
    public function getStdinOpen(): ?bool
    {
        return $this->stdinOpen;
    }

    /**
     * @param bool $stdinOpen
     *
     * @return self
     */
    public function setStdinOpen(?bool $stdinOpen): self
    {
        $this->stdinOpen = $stdinOpen;

        return $this;
    }

    /**
     * @return string
     */
    public function getStopGracePeriod(): ?string
    {
        return $this->stopGracePeriod;
    }

    /**
     * @param string $stopGracePeriod
     *
     * @return self
     */
    public function setStopGracePeriod(?string $stopGracePeriod): self
    {
        $this->stopGracePeriod = $stopGracePeriod;

        return $this;
    }

    /**
     * @return string
     */
    public function getStopSignal(): ?string
    {
        return $this->stopSignal;
    }

    /**
     * @param string $stopSignal
     *
     * @return self
     */
    public function setStopSignal(?string $stopSignal): self
    {
        $this->stopSignal = $stopSignal;

        return $this;
    }

    /**
     * @return string|string[]
     */
    public function getTmpfs()
    {
        return $this->tmpfs;
    }

    /**
     * @param string|string[] $tmpfs
     *
     * @return self
     */
    public function setTmpfs($tmpfs): self
    {
        $this->tmpfs = $tmpfs;

        return $this;
    }

    /**
     * @return bool
     */
    public function getTty(): ?bool
    {
        return $this->tty;
    }

    /**
     * @param bool $tty
     *
     * @return self
     */
    public function setTty(?bool $tty): self
    {
        $this->tty = $tty;

        return $this;
    }

    /**
     * @return int|object[]
     */
    public function getUlimits()
    {
        return $this->ulimits;
    }

    /**
     * @param int|object[] $ulimits
     *
     * @return self
     */
    public function setUlimits($ulimits): self
    {
        $this->ulimits = $ulimits;

        return $this;
    }

    /**
     * @return string
     */
    public function getUser(): ?string
    {
        return $this->user;
    }

    /**
     * @param string $user
     *
     * @return self
     */
    public function setUser(?string $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return string
     */
    public function getUsernsMode(): ?string
    {
        return $this->usernsMode;
    }

    /**
     * @param string $usernsMode
     *
     * @return self
     */
    public function setUsernsMode(?string $usernsMode): self
    {
        $this->usernsMode = $usernsMode;

        return $this;
    }

    /**
     * @return string[]|object[]
     */
    public function getVolumes(): ?array
    {
        return $this->volumes;
    }

    /**
     * @param string[]|object[] $volumes
     *
     * @return self
     */
    public function setVolumes(?array $volumes): self
    {
        $this->volumes = $volumes;

        return $this;
    }

    /**
     * @return string
     */
    public function getWorkingDir(): ?string
    {
        return $this->workingDir;
    }

    /**
     * @param string $workingDir
     *
     * @return self
     */
    public function setWorkingDir(?string $workingDir): self
    {
        $this->workingDir = $workingDir;

        return $this;
    }
}
